// Generated by gencpp from file motor_control/Motor2Request.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_MOTOR2REQUEST_H
#define MOTOR_CONTROL_MESSAGE_MOTOR2REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct Motor2Request_
{
  typedef Motor2Request_<ContainerAllocator> Type;

  Motor2Request_()
    : order(0)  {
    }
  Motor2Request_(const ContainerAllocator& _alloc)
    : order(0)  {
  (void)_alloc;
    }



   typedef int32_t _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::motor_control::Motor2Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::Motor2Request_<ContainerAllocator> const> ConstPtr;

}; // struct Motor2Request_

typedef ::motor_control::Motor2Request_<std::allocator<void> > Motor2Request;

typedef boost::shared_ptr< ::motor_control::Motor2Request > Motor2RequestPtr;
typedef boost::shared_ptr< ::motor_control::Motor2Request const> Motor2RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::Motor2Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::Motor2Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control::Motor2Request_<ContainerAllocator1> & lhs, const ::motor_control::Motor2Request_<ContainerAllocator2> & rhs)
{
  return lhs.order == rhs.order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control::Motor2Request_<ContainerAllocator1> & lhs, const ::motor_control::Motor2Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::Motor2Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::Motor2Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::Motor2Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::Motor2Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::Motor2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::Motor2Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::Motor2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6889063349a00b249bd1661df429d822";
  }

  static const char* value(const ::motor_control::Motor2Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6889063349a00b24ULL;
  static const uint64_t static_value2 = 0x9bd1661df429d822ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::Motor2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/Motor2Request";
  }

  static const char* value(const ::motor_control::Motor2Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::Motor2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 order\n"
;
  }

  static const char* value(const ::motor_control::Motor2Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::Motor2Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor2Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::Motor2Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::Motor2Request_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<int32_t>::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_MOTOR2REQUEST_H
