// Generated by gencpp from file motor_control/Motor2Response.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_MOTOR2RESPONSE_H
#define MOTOR_CONTROL_MESSAGE_MOTOR2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct Motor2Response_
{
  typedef Motor2Response_<ContainerAllocator> Type;

  Motor2Response_()
    : id(0)
    , position(0)  {
    }
  Motor2Response_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::motor_control::Motor2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::Motor2Response_<ContainerAllocator> const> ConstPtr;

}; // struct Motor2Response_

typedef ::motor_control::Motor2Response_<std::allocator<void> > Motor2Response;

typedef boost::shared_ptr< ::motor_control::Motor2Response > Motor2ResponsePtr;
typedef boost::shared_ptr< ::motor_control::Motor2Response const> Motor2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::Motor2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::Motor2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control::Motor2Response_<ContainerAllocator1> & lhs, const ::motor_control::Motor2Response_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control::Motor2Response_<ContainerAllocator1> & lhs, const ::motor_control::Motor2Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::Motor2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::Motor2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::Motor2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::Motor2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::Motor2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::Motor2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::Motor2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "833110e1050ad82a9398ab64153a6a86";
  }

  static const char* value(const ::motor_control::Motor2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x833110e1050ad82aULL;
  static const uint64_t static_value2 = 0x9398ab64153a6a86ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::Motor2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/Motor2Response";
  }

  static const char* value(const ::motor_control::Motor2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::Motor2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 position\n"
;
  }

  static const char* value(const ::motor_control::Motor2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::Motor2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::Motor2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::Motor2Response_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_MOTOR2RESPONSE_H
